global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: megaspell-server-registry
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['megaspell-server-registry:8080']